FROM python:3.12

# Налаштовуємо змінні для Python та Poetry
ENV PYTHONUNBUFFERED=1 \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=false

WORKDIR /app

# Встановлюємо Poetry
RUN pip install poetry==2.0.1

# Копіюємо тільки файли залежностей
COPY pyproject.toml poetry.lock ./

# Встановлюємо залежності 
RUN poetry install --only main --no-root

# Копіюємо весь код
COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]